---
title: "AB hists"
author: "Brian J. Knaus"
date: "June 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data

## P. andina

```{r}
pand <- vector(mode = 'list', length = 0)
load("../ab_RData_min20_max80/pand/P13803_ab.RData")
pand$P13803 <- ab1
load("../ab_RData_min20_max80/pand/PaX_ab.RData")
pand$PaX <- ab1
```

## P. infestans

```{r}
pinf <- vector(mode = 'list', length = 0)
load("../ab_RData_min20_max80/pinf/DDR7602_ab.RData")
pinf$DDR7602 <- ab1
load("../ab_RData_min20_max80/pinf/NL07434_ab.RData")
pinf$NL07434 <- ab1
load("../ab_RData_min20_max80/pinf/P13626_ab.RData")
pinf$P13626 <- ab1
load("../ab_RData_min20_max80/pinf/P17777_ab.RData")
pinf$P17777 <- ab1
```


## P. capsici


```{r}
pcap <- vector(mode = 'list', length = 0)
load("../ab_RData_min20_max80/pcap/Pc1E8_ab.RData")
pcap$Pc1E8 <- ab1
load("../ab_RData_min20_max80/pcap/Pc33e_ab.RData")
pcap$Pc33e <- ab1
load("../ab_RData_min20_max80/pcap/Pc377_ab.RData")
pcap$Pc377 <- ab1
load("../ab_RData_min20_max80/pcap/Pc389_ab.RData")
pcap$Pc389 <- ab1
```


## P. parasitica


```{r}
ppar <- vector(mode = 'list', length = 0)
load("../ab_RData_min20_max80/ppar/INRA-310_ab.RData")
ppar$INRA310 <- ab1
load("../ab_RData_min20_max80/ppar/J01A1_ab.RData")
ppar$J01A1 <- ab1
load("../ab_RData_min20_max80/ppar/P10297_ab.RData")
ppar$P10297 <- ab1
load("../ab_RData_min20_max80/ppar/P1569_ab.RData")
ppar$P1569 <- ab1
```


# Plot

## P. capsici


```{r}

#pdf("pcap_abhist.pdf", width = 6.5, height = 2)
#pdf("pcap_abhist.pdf", width = 3.75, height = 1, pointsize = 10)

par(mfcol=c(1,4))
#par(mar=c(1,4,2,0.5))
par(mar=c(1,1,2,0.5))

hist(pcap$Pc1E8[,'Pc1E8_ab2'], breaks = seq(0,1,by=0.02), col = "#fdbf6f", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#fdbf6f", las = 2)
hist(pcap$Pc1E8[,'Pc1E8_ab1'], breaks = seq(0,1,by=0.02), col = "#ff7f00", add = TRUE, border = "#ff7f00")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,4e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "Pc1E8", line = 0.5)

hist(pcap$Pc33e[,'Pc33e_ab2'], breaks = seq(0,1,by=0.02), col = "#fdbf6f", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#fdbf6f", las = 2)
hist(pcap$Pc33e[,'Pc33e_ab1'], breaks = seq(0,1,by=0.02), col = "#ff7f00", add = TRUE, border = "#ff7f00")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,5e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "Pc33e", line = 0.5)

hist(pcap$Pc377[,'Pc377_ab2'], breaks = seq(0,1,by=0.02), col = "#fdbf6f", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#fdbf6f", las = 2)
hist(pcap$Pc377[,'Pc377_ab1'], breaks = seq(0,1,by=0.02), col = "#ff7f00", add = TRUE, border = "#ff7f00")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,6e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "Pc377", line = 0.5)

hist(pcap$Pc389[,'Pc389_ab2'], breaks = seq(0,1,by=0.02), col = "#fdbf6f", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#fdbf6f", las = 2)
hist(pcap$Pc389[,'Pc389_ab1'], breaks = seq(0,1,by=0.02), col = "#ff7f00", add = TRUE, border = "#ff7f00")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,5e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "Pc389", line = 0.5)

#dev.off()

par(mfcol=c(1,1))
par(mar=c(5,4,4,2))

```




## P. parasitica


```{r}

#pdf("ppar_abhist.pdf", width = 6.5, height = 2)
#pdf("ppar_abhist.pdf", width = 3.75, height = 1, pointsize = 10)

par(mfcol=c(1,4))
#par(mar=c(1,4,2,0.5))
par(mar=c(1,1,2,0.5))

hist(ppar$INRA310[,'INRA-310_ab2'], breaks = seq(0,1,by=0.02), col = "#cab2d6", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#cab2d6", las = 2)
hist(ppar$INRA310[,'INRA-310_ab1'], breaks = seq(0,1,by=0.02), col = "#6a3d9a", add = TRUE, border = "#6a3d9a")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,2e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "INRA-310", line = 0.5)

hist(ppar$J01A1[,'J01A1_ab2'], breaks = seq(0,1,by=0.02), col = "#cab2d6", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#cab2d6", las = 2)
hist(ppar$J01A1[,'J01A1_ab1'], breaks = seq(0,1,by=0.02), col = "#6a3d9a", add = TRUE, border = "#6a3d9a")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,2e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "J01A1", line = 0.5)

hist(ppar$P10297[,'P10297_ab2'], breaks = seq(0,1,by=0.02), col = "#cab2d6", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#cab2d6", las = 2)
hist(ppar$P10297[,'P10297_ab1'], breaks = seq(0,1,by=0.02), col = "#6a3d9a", add = TRUE, border = "#6a3d9a")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,2e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "P10297", line = 0.5)

hist(ppar$P1569[,'P1569_ab2'], breaks = seq(0,1,by=0.02), col = "#cab2d6", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#cab2d6", las = 2)
hist(ppar$P1569[,'P1569_ab1'], breaks = seq(0,1,by=0.02), col = "#6a3d9a", add = TRUE, border = "#6a3d9a")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,2e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "P1569", line = 0.5)

# hist(ppar$P1976[,'P1976_ab2'], breaks = seq(0,1,by=0.02), col = "#cab2d6", xaxt="n", main="", xlab = "", ylab="", border = "#cab2d6", las = 2)
# hist(ppar$P1976[,'P1976_ab1'], breaks = seq(0,1,by=0.02), col = "#6a3d9a", add = TRUE, border = "#6a3d9a")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
# #axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# #abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "P1976", line = 0.5)

#dev.off()

par(mfcol=c(1,1))
par(mar=c(5,4,4,2))


```



## P. infestans


```{r}

#pdf("pinf_abhist.pdf", width = 6.5, height = 2)
#pdf("pinf_abhist.pdf", width = 3.75, height = 1, pointsize = 10)

par(mfcol=c(1,4))
#par(mar=c(1,4,2,0.5))
par(mar=c(1,1,2,0.5))

hist(pinf$P17777[,'P17777_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
hist(pinf$P17777[,'P17777_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,3e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "P17777", line = 0.5)

hist(pinf$NL07434[,'NL07434_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
hist(pinf$NL07434[,'NL07434_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,3e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "NL07434", line = 0.5)

# hist(pinf$PIC97750[,'PIC97750_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
# hist(pinf$PIC97750[,'PIC97750_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
# #axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# #abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "PIC97750", line = 0.5)

hist(pinf$DDR7602[,'DDR7602_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
hist(pinf$DDR7602[,'DDR7602_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,4e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "DDR7602", line = 0.5)

# hist(pinf$blue13[,'06_3928A_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
# hist(pinf$blue13[,'06_3928A_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
# #axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# #abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "06_3928A", line = 0.5)

hist(pinf$P13626[,'P13626_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
hist(pinf$P13626[,'P13626_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,4e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "P13626", line = 0.5)


#dev.off()

par(mfcol=c(1,1))
par(mar=c(5,4,4,2))




# hist(pinf$BL2009P4[,'BL2009P4_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
# hist(pinf$BL2009P4[,'BL2009P4_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "BL2009P4", line = 0.5)
# 
# hist(pinf$LBUS[,'LBUS_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
# hist(pinf$LBUS[,'LBUS_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "LBUS", line = 0.5)
# 
# hist(pinf$P13527[,'P13527_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
# hist(pinf$P13527[,'P13527_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "P13527", line = 0.5)
# 
# hist(pinf$P8144[,'P8144_ab2'], breaks = seq(0,1,by=0.02), col = "#a6cee3", xaxt="n", main="", xlab = "", ylab="", border = "#a6cee3", las = 2)
# hist(pinf$P8144[,'P8144_ab1'], breaks = seq(0,1,by=0.02), col = "#1f78b4", add = TRUE, border = "#1f78b4")
# axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
# abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
# title(main = "P8144", line = 0.5)



```



## P. andina


```{r}

#pdf("pand_abhist.pdf", width = 6.5, height = 2)
#pdf("pand_abhist.pdf", width = 3.75, height = 1, pointsize = 10)

par(mfcol=c(1,4))
#par(mar=c(1,4,2,0.5))
par(mar=c(1,1,2,0.5))

hist(pand$P13803[,'P13803_ab2'], breaks = seq(0,1,by=0.02), col = "#ffff99", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#ffff99", las = 2)
hist(pand$P13803[,'P13803_ab1'], breaks = seq(0,1,by=0.02), col = "#b15928", add = TRUE, border = "#b15928")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,10e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "P13803", line = 0.5)

hist(pand$PaX[,'PaX_ab2'], breaks = seq(0,1,by=0.02), col = "#ffff99", xaxt="n", yaxt="n", main="", xlab = "", ylab="", border = "#ffff99", las = 2)
hist(pand$PaX[,'PaX_ab1'], breaks = seq(0,1,by=0.02), col = "#b15928", add = TRUE, border = "#b15928")
axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=FALSE, las=2)
axis(side=2, at=seq(0,10e4, by=1e4), labels=FALSE, las=2)
#axis(side=1, at=c(0,0.2,0.25,0.333,0.5,0.666,0.75, 0.8,1), labels=c(0,"","1/4","1/3","1/2","2/3","3/4","",1), las=2)
#abline(v=c(1/3,1/2,2/3), col="#808080", lwd=2)
title(main = "PaX", line = 0.5)

#dev.off()

par(mfcol=c(1,1))
par(mar=c(5,4,4,2))


```




