---
title: "AARD Violin Plots"
author: "Brian J. Knaus"
date: "May 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```


## Data


```{r, results='hide'}
library(vcfR)
vcf <- read.vcfR("../aard_ploid/pitg_cnv_20191206.vcf.gz", checkFile = FALSE)
```


```{r}
vcf
queryMETA(vcf)
```


## AARD


```{r}
aard <- extract.gt(vcf, element = "AARD", as.numeric = TRUE)
myAard <- colMeans(aard)
vcf  <- vcf[,sample = names(myAard[myAard >= 12 & !is.na(myAard)])]
vcf
```



## Filter taxa


Omit non-infestans

```{r}
vcf <- vcf[,grep("F18|00Ip5|Ipom_1.2|Ipom_2.4|Pipo5|P3001|00Ip5|Ipom_1.2|Ipom_2.4|Pipo5|P3001|00M_410|CBS.678.85|PIC99167|Pmir5|PIC99114|P7722|CJ01A1|INRA.310|P10297|P1569|P1976|PaX|EC3425|EC3394|P13803", colnames(vcf@gt), invert = TRUE)]
vcf
```


Omit 1306

```{r}
vcf <- vcf[,grep("1306", colnames(vcf@gt), invert = TRUE)]
vcf
```



## Violin plot


```{r}
library(reshape2)
library(ggplot2) 
library(cowplot)

aard <- extract.gt(vcf, element = "AARD", as.numeric = TRUE)
aard <- aard[,sort.int(colMeans(aard), decreasing = TRUE, index.return = TRUE)$ix]

dpf <- melt(aard, varnames=c('Index', 'Sample'), value.name = 'Depth', na.rm=TRUE)
dpf <- dpf[ dpf$Depth > 0,]


samps_per_row <- 24
myRows <- ceiling(length(levels(dpf$Sample))/samps_per_row)
myList <- vector(mode = "list", length = myRows)

for(i in 1:myRows){
  myIndex <- c(i*samps_per_row - samps_per_row + 1):c(i*samps_per_row)
  myIndex <- myIndex[myIndex <= length(levels(dpf$Sample))]
  myLevels <- levels(dpf$Sample)[myIndex]
  myRegex <- paste(myLevels, collapse = "$|^")
  myRegex <- paste("^", myRegex, "$", sep = "")
  myList[[i]] <- dpf[grep(myRegex, dpf$Sample),]
  myList[[i]]$Sample <- factor(myList[[i]]$Sample)
}

# Create the plot.
myPlots <- vector(mode = "list", length = myRows)
for(i in 1:myRows){
  myPlots[[i]] <- ggplot(myList[[i]], aes(x=Sample, y=Depth)) + 
                  geom_violin(fill="#808080", color="#808080", adjust=1.0, scale = "count", trim=TRUE)

  myPlots[[i]] <- myPlots[[i]] + theme_bw()
  myPlots[[i]] <- myPlots[[i]] + theme(axis.title.x = element_blank(), 
                  axis.text.x = element_blank())
  myPlots[[i]] <- myPlots[[i]] + theme(axis.title.y = element_blank())
  myPlots[[i]] <- myPlots[[i]] + scale_y_continuous(trans=scales::log2_trans(), 
                  breaks=c(1, 10, 100, 800))
  myPlots[[i]] <- myPlots[[i]] + theme( panel.grid.major.y=element_line(color = "#A9A9A9", size=0.2) )
  myPlots[[i]] <- myPlots[[i]] + theme( panel.grid.minor.y=element_blank() )
  myPlots[[i]] <- myPlots[[i]] + theme( panel.grid.major.x=element_line(size=0.2) )

}

myPlots[[1]] <- myPlots[[1]] + theme(plot.margin = unit(c(0.1,0.1,0.3,0.7), "cm")) 
myPlots[[2]] <- myPlots[[2]] + theme(plot.margin = unit(c(0.1,0.1,0.7,0.7), "cm")) 

# (top, right, bottom, left)
```


```{r}
# Plot the plot.

plot_grid(plotlist = myPlots, ncol=1, nrow=2) + draw_label(label = "Isolate", x=0.5, y=0.03) + draw_label("AARD", x=0.01, y=0.5, angle=90)

```


```{r}
# Plot the plot.
#pdf(file='pinf_aard_violin.pdf', width = 3.25, height = 3.25, pointsize = 10)
#svg(file='pinf_aard_violin.svg', width = 3.25, height = 3.25, pointsize = 10)
plot_grid(plotlist = myPlots, ncol=1, nrow=2) + draw_label(label = "Isolate", x=0.5, y=0.03) + draw_label("AARD", x=0.04, y=0.5, angle=90)
#
#dev.off()

```



