---
title: "Ploid vplot"
author: "Brian J. Knaus"
date: "March 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```

## R Markdown


```{r}
x <- read.table("pmat.csv", sep = ",", header = TRUE, row.names = 1, na.strings = "")
```


## Omit NA


```{r}
#
x <- x[-1,]
```

## Make percent

```{r}
ngene <- colSums(x)

x['2',] <- x['2',]/ngene
x['3',] <- x['3',]/ngene
```


```{r}
grep("^M.0182896$|^Pi1889$|^P8140$|^P13346$", colnames(x), value = TRUE)
grep("^P8141$|^Kew126$|^P6515$|^DDR7602$|^Kew122$|^LBUS$", colnames(x), value = TRUE)
grep("^RS2009P1$|^US0400009$|^FP-GCC$|^P10127$|^US100006$|^P17777$|^IN2009T1$|^BL2009P4$|^FL2009P4$|^ND822Pi$", colnames(x), value = TRUE)
grep("^P3685$|^P6634$|^P7036$|^P3683$|^P8143$|^P6636$|^P8144$|^PIC97207$|^PIC97605$|^PIC97630$|^PIC97146$|^PIC97335$|^PIC97785$|^PIC97750$|^P10650$|^PIC98372$", colnames(x), value = TRUE)
grep("^P8844$|^PCZ026$|^PCZ098$|^PCO038$|^PCZ033$|^P13198$|^P13527$|^P13626$", colnames(x), value = TRUE)
grep("^P6570$|^06_3928A$|^NL07434$", colnames(x), value = TRUE)


x2 <- t(x[,grep("^M.0182896$|^Pi1889$|^P8140$|^P13346$", colnames(x))])
x2 <- cbind(x2, rep("HERB-1", times = 4))
colnames(x2)[ncol(x2)] <- "group"
#colnames(x2)[6] <- "group"


tmp <- t(x[,grep("^P8844$|^P8141$|^Kew126$|^P6515$|^DDR7602$|^Kew122$|^LBUS$", colnames(x))])
tmp <- cbind(tmp, rep("US-1", times = 7))
x2 <- rbind(x2, tmp)

tmp <- t(x[,grep("^RS2009P1$|^US0400009$|^FP[[:punct:]]GCC$|^P10127$|^BL2009P4$|^FL2009P4$|^ND822Pi$", colnames(x))])
tmp <- cbind(tmp, rep("US lineages", times = 7))
#tmp <- cbind(tmp, rep("US lineages", times = 10))
x2 <- rbind(x2, tmp)

tmp <- t(x[,grep("^^US100006$|^P17777$|^IN2009T1$", colnames(x))])
tmp <- cbind(tmp, rep("US-22", times = 3))
x2 <- rbind(x2, tmp)

tmp <- t(x[,grep("^P3685$|^P6634$|^P7036$|^P3683$|^P8143$|^P6636$|^P8144$|^PIC97207$|^PIC97605$|^PIC97630$|^PIC97146$|^PIC97335$|^PIC97785$|^PIC97750$|^P10650$|^PIC98372$", colnames(x))])
tmp <- cbind(tmp, rep("Mexico", times = 16))
x2 <- rbind(x2, tmp)

tmp <- t(x[,grep("^PCZ026$|^PCZ098$|^PCO038$|^PCZ033$|^P13198$|^P13527$|^P13626$", colnames(x))])
tmp <- cbind(tmp, rep("S. America", times = 7))
x2 <- rbind(x2, tmp)

tmp <- t(x[,grep("^P6570$|06[[:punct:]]3928A$|^NL07434$", colnames(x))])
tmp <- cbind(tmp, rep("Europe", times = 3))
x2 <- rbind(x2, tmp)
```


```{r}
x2 <- as.data.frame(x2)
#x2$group

#x2$`2` <- as.numeric(as.character(x2$`2`))/18179
#x2$`3` <- as.numeric(as.character(x2$`3`))/18179
#
x2$`2` <- as.numeric(as.character(x2$`2`))
#
x2$`3` <- as.numeric(as.character(x2$`3`))

colnames(x2)[grep('2', colnames(x2))] <- "dip"
colnames(x2)[grep('3', colnames(x2))] <- "trip"

```


```{r}
#x2$group <- factor(as.character(x2$group), levels = c("HERB-1", "US-1", "US lineages", "Mexico", "S. America", "Europe"))
#x2$group <- factor(as.character(x2$group), levels = c("HERB-1", "US-1", "US lineages", "US-22", "Mexico", "S. America", "Europe"))

#x2$group <- factor(as.character(x2$group), levels = c("Mexico", "S. America", "Europe", "HERB-1", "US-1", "US lineages", "US-22"))
x2$group <- factor(as.character(x2$group), levels = c("Mexico", "S. America", "HERB-1", "US-1", "US lineages", "US-22", "Europe"))
```



```{r}
library(ggplot2)
library(grid)

#p <- ggplot(x2, aes(x=group, y=dip, fill=group))
p <- ggplot(x2, aes(x=group, y=trip, fill=group, color = group))
#p <- p + geom_violin(adjust=1.5, scale = "count", trim=TRUE)
#p <- p + geom_violin(adjust=1.00)
p <- p + geom_violin(adjust=0.80, lwd = 0.3)
#p <- p + scale_fill_manual(values = c("#B8860B", "#CD5C5C", "#F08080", "#FFA07A", "#32CD32", "#FF8C00", "#1E90FF"))
p <- p + scale_fill_manual(values = c("#32CD32", "#FFCC99", "#B8860B", "#CD5C5C", "#F08080", "#FFA07A", "#87CEFA"))
#p <- p + scale_color_manual(values = c("#32CD32", "#FF8C00", "#B8860B", "#CD5C5C", "#F08080", "#FFA07A", "#1E90FF"))
p <- p + scale_color_manual(values = c("#228B22", "#FF8C00", "#8B4513", "#8B0000", "#CD5C5C", "#CD5C5C", "#0000CD"))

p <- p + theme_bw()
#
p <- p + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 60, hjust = 1))
p <- p + scale_y_continuous(breaks=c(0, 0.25, 0.5, 0.75), labels = c("0%","25%","50%","75%")) 


#p <- p + theme(axis.text.x = element_text(angle = 60, hjust = 1))
#p <- p + theme(axis.title.y = element_blank())
#p <- p + ylab("Proportion of diploid genes")
#p <- p + ylab("Proportion of triploid genes")
p <- p + ylab("Triploid genes")
#p <- p + xlab("Population")
p <- p + theme(legend.position="none")
#p <- p + stat_summary(fun.data=mean_sdl, geom="pointrange", color="black")
#p <- p + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.6, fill = "#C0C0C0aa", color = "#808080")
p <- p + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.6, fill = "#C0C0C0aa", color = "#696969")
#p <- p + stat_summary(fun.y=median, geom="point", shape = 45, size=10, color="black")
#p <- p + geom_hline(aes(yintercept=-0.1))

p <- p + theme(plot.margin = unit(c(0.4, 0.4, 1.6, 0.4), "lines"))

p <- p + annotation_custom(
      grob = textGrob(label = "Sexual", hjust = 0.5, gp = gpar(cex = 0.6, font = 1)),
      ymin = -0.4, ymax = -0.4, xmin = 0.7, xmax = 0.7)

p <- p + annotation_custom(
      grob = textGrob(label = "Clonal", hjust = 0.5, gp = gpar(cex = 0.6, font = 1)),
      ymin = -0.4, ymax = -0.4, xmin = 3.5, xmax = 3.5)

p <- p + annotation_custom(
      grob = linesGrob(gp = gpar(cex = 1.0, lwd=2)),
      ymin = -0.36, ymax = -0.36, xmin = 0.4, xmax = 1.0)

p <- p + annotation_custom(
      grob = linesGrob(gp = gpar(cex = 1.0, lwd=2)),
      ymin = -0.36, ymax = -0.36, xmin = 1.4, xmax = 6.0)


# Code to override clipping
gt <- ggplot_gtable(ggplot_build(p))
gt$layout$clip[gt$layout$name == "panel"] <- "off"
```


```{r}
#png("ploid_vplot.png", width = 3.25, height = 3.25, units = "in", res = 300)
#pdf("ploid_vplot.pdf", width = 3.25, height = 3.25)
#p
grid.draw(gt)
#
#dev.off()

```



