---
title: "Ia"
author: "Brian J. Knaus"
date: "May 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```


```{r}
library(poppr)
data(Pinf)
strata(Pinf)

NAia <- ia(Pinf[Pinf$strata$Continent=="North America",], sample = 999, valuereturn = TRUE)
SAia <- ia(Pinf[Pinf$strata$Continent=="South America",], sample = 999, valuereturn = TRUE)

```



```{r}
#svg("pinfia.svg", width=3.25, height=3.25)
#pdf("pinfia.pdf", width=3.25, height=3.25)

par(mfrow=c(2,1))


par(mar=c(0,0,0,0))
par(oma=c(3,3,0.1,0.1))

plot(density(SAia$samples$Ia), xlim = c(-0.3, 3), main="", xlab="", ylab="", type = "n", xaxt="n")
polygon(density(SAia$samples$Ia), col="#DC143C22", border="#DC143C")
lines(x=c(SAia$index['Ia'], SAia$index['Ia']), y=c(0,3), lwd=4, col="#DC143C")
legend('topright', legend=c("S. America"), fill=c("#DC143C"), bty="n")

plot(density(SAia$samples$Ia), xlim = c(-0.3, 3), main="", xlab="", ylab="", type = "n", xaxt="n")
polygon(density(NAia$samples$Ia), col="#00808022", border="#008080")
lines(x=c(NAia$index['Ia'], NAia$index['Ia']), y=c(0,3), lwd=4, col="#008080")
legend('topright', legend=c("Mexico"), fill=c("#008080"), bty="n")
axis(side=1, at=seq(0,3,by=1))

title(xlab="Index of Association", outer = TRUE, line=2)
title(ylab="Density", outer = TRUE, line=2)

#dev.off()

```



