---
title: "Sample size"
author: "Brian Knaus"
date: "May 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```

## Sample size


```{r}
df <- data.frame(pop=c("Mexico", "S. America", "HERB-1", "US-1", "US-8", "US-11", "US-18", "US-22", "US-23", "US-24", "Europe"),
                Count=c(16, 7, 4, 7, 2, 1, 1, 3, 2, 1, 3))
df$pop <- factor(df$pop, levels = c('Mexico','S. America','HERB-1', "US-1", "US-8", "US-11", "US-18", "US-22", "US-23", "US-24", "Europe"))
head(df)
```



```{r}
library(ggplot2)
library(grid)
# Basic barplot
p <- ggplot(data=df, aes(x=pop, y=Count, fill=pop))
p <- p + geom_bar(stat="identity")
#p <- p + scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9"))
p <- p + scale_fill_manual(values = c("#228B22", "#FF8C00", "#8B4513", "#8B0000", "#CD5C5C", "#CD5C5C", "#CD5C5C", "#CD5C5C", "#CD5C5C", "#CD5C5C", "#0000CD"))
p <- p + theme_bw()
p <- p + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 60, hjust = 1))
p <- p + theme(legend.position="none")
p <- p + ylab("Sample count")

p <- p + theme(plot.margin = unit(c(0.4, 0.4, 1.6, 0.4), "lines"))

p <- p + annotation_custom(
      grob = textGrob(label = "Sexual", hjust = 0.5, gp = gpar(cex = 1.0, font = 1)),
      ymin = -7.3, ymax = -7.3, xmin = -0.4, xmax = -0.4)

p <- p + annotation_custom(
      grob = textGrob(label = "Clonal", hjust = 0.5, gp = gpar(cex = 1.0, font = 1)),
      ymin = -7.3, ymax = -7.3, xmin = 5.5, xmax = 5.5)

p <- p + annotation_custom(
      grob = linesGrob(gp = gpar(cex = 1.0, lwd=2)),
      ymin = -6.5, ymax = -6.5, xmin = -1.0, xmax = 0.5)

p <- p + annotation_custom(
      grob = linesGrob(gp = gpar(cex = 1.0, lwd=2)),
      ymin = -6.5, ymax = -6.5, xmin = 1.0, xmax = 11.0)

# Code to override clipping
gt <- ggplot_gtable(ggplot_build(p))
gt$layout$clip[gt$layout$name == "panel"] <- "off"

```


```{r}
#svg(filename = "sample.svg", width = 3.25, height = 3.25)
#pdf("sample.pdf", width = 3.25, height = 3.25)
#p
grid.draw(gt)
#
#dev.off()
```




