---
title: "Add DFEAB"
author: "Brian J. Knaus"
date: "February 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
```


## DFEAB


Previously we have called ploidy based on allele balance.
Here we create a measure of confidence in this ploidy by measuring the deviation from the expected value.
This number is the divided by half of its ploidy bins width so that it scales from zero to one.


```{r, results='hide'}
library(vcfR)
vcf <- read.vcfR("pitg_cnv.vcf.gz", checkFile = FALSE)
```


```{r}
vcf
queryMETA(vcf)
```



```{r}
alb <- extract.gt(vcf, element = "ALB", as.numeric = TRUE)
abp <- extract.gt(vcf, element = "ABP", as.numeric = TRUE)

abp[1:3,1:6]
table(abp, useNA = "always")
#sum(is.na(abp))
```


## Plot

```{r}
plot(c(0.5, 1), c(0,1), type = "n", xaxt = "n", xlab = "", ylab = "")
axis(side = 1, at = c(1/2, 2/3, 3/4, 4/5), labels = c('1/2', '2/3', '3/4', '4/5'))

abline(v=c(1/2, 2/3, 3/4, 4/5))
abline(v=c(7/12, 17/24, 31/40, 33/40), lty=3, col ="#B22222")

text(x=7/12, y=0.1, labels = "7/12", srt = 90)
text(x=17/24, y=0.1, labels = "17/24", srt = 90)
text(x=31/40, y=0.1, labels = "31/40", srt = 90)
text(x=33/40, y=0.1, labels = "33/40", srt = 90)

#x1 <- matrix(1:4, ncol=2)
#x2 <- matrix(1:4, ncol=2)
#x2[1,1] <- NA
#x1 + x2

```


```{r}

#pdf("critical.pdf", width=7, height=5)
plot(c(0.0, 1), c(0,1), type = "n", xaxt = "n", xlab = "", ylab = "")

myCalls <-  c(1/5, 1/4, 1/3, 1/2, 2/3, 3/4, 4/5)
axis(side = 1, at = myCalls, labels = c('1/5', '1/4', '1/3','1/2', '2/3', '3/4', '4/5'), las=2)

#abline(v=c(1/2, 2/3, 3/4, 4/5))
abline(v=myCalls)

abline(v=c(7/40, 9/40, 7/24, 5/12), lty=3, col ="#B22222")
abline(v=c(7/12, 17/24, 31/40, 33/40), lty=3, col ="#B22222")

text(x=7/40, y=0.1, labels = "7/40", srt = 90)
text(x=9/40, y=0.1, labels = "9/40", srt = 90)
text(x=7/24, y=0.1, labels = "7/24", srt = 90)
text(x=5/12, y=0.1, labels = "5/12", srt = 90)

text(x=7/12, y=0.1, labels = "7/12", srt = 90)
text(x=17/24, y=0.1, labels = "17/24", srt = 90)
text(x=31/40, y=0.1, labels = "31/40", srt = 90)
text(x=33/40, y=0.1, labels = "33/40", srt = 90)
#dev.off()

```



## Calculate DFE


```{r}
hist(alb[,'P17777'], col = "#c51b8a")
abline( v = c(7/12, 17/24, 31/40, 33/40), col = "#de2d26", lwd = 2 )
hist(alb[,'P17777'][abp[,'P17777'] == 4], col = "#c51b8a")
abline( v = c(7/12, 17/24, 31/40, 33/40), col = "#de2d26", lwd = 2 )

hist(alb[,'P13626'], col = "#c51b8a")
abline( v = c(7/12, 17/24, 31/40, 33/40), col = "#de2d26", lwd = 2 )
hist(alb[,'P13626'][abp[,'P13626'] == 4], col = "#c51b8a")
abline( v = c(7/12, 17/24, 31/40, 33/40), col = "#de2d26", lwd = 2 )

dfe <- 1/abp
dfe <- 1- dfe
dfe <- alb - dfe
#dfe <- abs(dfe)

boxplot(dfe, las = 3)

#div <- abp
```


```{r}
hist(dfe[,'P17777'])
hist(dfe[,'P13626'])
```



Scale to bin width


```{r}
dfe2 <- dfe

# Diploid
#
dfe2[ abp == 2 & !is.na(abp) ] <- dfe[ abp == 2 & !is.na(abp) ] / (1/12)

# Triploid
#
dfe2[ abp == 3 & dfe <= 0 & !is.na(abp) ] <- dfe[ abp == 3 & dfe <= 0 & !is.na(abp) ] / (1/12)
#
dfe2[ abp == 3 & dfe > 0 & !is.na(abp) ] <- dfe[ abp == 3 & dfe > 0 & !is.na(abp) ] / (1/24)

# Tetraploid
#
dfe2[ abp == 4 & dfe <= 0 & !is.na(abp) ] <- dfe[ abp == 4 & dfe <= 0 & !is.na(abp) ] / (1/24)
#
dfe2[ abp == 4 & dfe > 0 & !is.na(abp) ] <- dfe[ abp == 4 & dfe > 0 & !is.na(abp) ] / (1/40)

# Pentaploid
#
dfe2[ abp == 5 & !is.na(abp) ] <- dfe[ abp == 5 & !is.na(abp) ] / (1/40)

#
dfe2 <- abs(dfe2)
```



## Sanity check


```{r}
samp <- "P17777"
par(mfrow = c(2,3))
hist(dfe2[,samp], col = "#2ca25f", main = "All")
hist(dfe2[,samp][abp[,samp] == 2], main = "2x", ylab = "", col = "#2ca25f")
hist(dfe2[,samp][abp[,samp] == 3], main = "3x", ylab = "", col = "#2ca25f")
hist(dfe2[,samp][abp[,samp] == 4], main = "4x", ylab = "", col = "#2ca25f")
hist(dfe2[,samp][abp[,samp] == 5], main = "5x", ylab = "", col = "#2ca25f")
par(mfrow = c(1,1))

samp <- "P13626"
par(mfrow = c(2,3))
hist(dfe2[,samp], col = "#2ca25f", main = "All")
hist(dfe2[,samp][abp[,samp] == 2], main = "2x", ylab = "", col = "#2ca25f")
hist(dfe2[,samp][abp[,samp] == 3], main = "3x", ylab = "", col = "#2ca25f")
hist(dfe2[,samp][abp[,samp] == 4], main = "4x", ylab = "", col = "#2ca25f")
hist(dfe2[,samp][abp[,samp] == 5], main = "5x", ylab = "", col = "#2ca25f")
par(mfrow = c(1,1))


```



```{r, fig.width=12}

#boxplot(dfe2/0.08, las = 3, col = 2:8)
boxplot(dfe2, las = 3, col = 2:8, main = "All")
boxplot(dfe2[ abp < 5 & !is.na(abp), drop = FALSE ], las = 3, col = 2:8, main = "All (<5)")


dip <- dfe2
is.na( dip[ abp != 2 & !is.na(abp) ] ) <- TRUE
boxplot(dip, las = 3, col = 2:8, main = "Diploid")

trip <- dfe2
is.na( trip[ abp != 3 & !is.na(abp) ] ) <- TRUE
boxplot(trip, las = 3, col = 2:8, main = "Triploid")

tet <- dfe2
is.na( tet[ abp != 4 & !is.na(abp) ] ) <- TRUE
boxplot(tet, las = 3, col = 2:8, main = "Tetraploid")



#boxplot(dfe2[ abp == 2 & !is.na(dfe2) ], las = 3, col = 2:8)

```


```{r}
mat1 <- matrix(rep(2:4, times=4), ncol = 4, byrow = TRUE)
is.na(mat1[2,2:3]) <- TRUE
mat2 <- matrix(rep(LETTERS[2:4], times=4), ncol = 4, byrow = TRUE)
mat2[ mat1 == 2 & !is.na(mat1) ]
```


```{r}
par(mfrow = c(2,2))

hist(dfe2[ abp == 2 & !is.na(abp)], main = "2x")
hist(dfe2[ abp == 3 & !is.na(abp)], main = "3x")
hist(dfe2[ abp == 4 & !is.na(abp)], main = "4x")
hist(dfe2[ abp == 5 & !is.na(abp)], main = ">4x")

#hist(dfe2[ abp == 2 & !is.na(abp)], xlim = c(-1/12, 1/12)/2)
#hist(dfe2[ abp == 3 & !is.na(abp)], xlim = c(-1/12, 1/24)/2)
#hist(dfe2[ abp == 4 & !is.na(abp)], xlim = c(-1/22, 1/40)/2)
#hist(dfe2[ abp == 5 & !is.na(abp)], xlim = c(-1/40, 1/40)/2)

par(mfrow = c(1,1))
```


## Update VCF


```{r}
FORMAT <- vcf@gt[,1]
gt <- vcf@gt[,-1]

dfe2[is.na(dfe2)] <- "."


gt <- matrix(paste(gt, dfe2, sep = ":"),  nrow=nrow(gt), dimnames=dimnames(gt))

FORMAT <- paste(FORMAT, "ABPDFE", sep = ":")

vcf@gt <- cbind(FORMAT, gt)

vcf@meta <- c(vcf@meta, "##FORMAT=<ID=ABPDFE,Number=1,Type=Float,Description=\"Allele Balance PLoid Deviation From Expectation\">")

vcf
```


```{r}
#write.vcf(vcf, file="pitg_cnv_abpdfe.vcf.gz")
```